version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.08
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Login to dockerhub and export environment variables
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

            echo 'export IMAGE_NAME="philbug/revanced-builder"' >> $BASH_ENV
            echo 'export FILE_PATH="."' >> $BASH_ENV

      - run:
          name: Build image
          command: |
            docker build -f $FILE_PATH/Dockerfile -t $IMAGE_NAME:${CIRCLE_SHA1:0:10} -t $IMAGE_NAME:latest $FILE_PATH

      - run:
          name: Push image
          command: |
            docker push $IMAGE_NAME --all-tags
